window.COMPONENTS_CONFIG = {
  THEME_COLOR: ko.observable('#007bff'),
  LANGUAGE: ko.observable('ko'),
  CSS: {
    BACKGROUND_COLOR: {
      'Common/White': 'background-white',
      'Gray/01': 'background-gray-01',
      'Gray/02': 'background-gray-02',
      'Gray/03': 'background-gray-03',
      'Gray/04': 'background-gray-04',
      'Gray/05': 'background-gray-05',
      'Gray/06': 'background-gray-06',
      'Gray/07': 'background-gray-07',
      'Gray/08': 'background-gray-08',
      'Gray/09': 'background-gray-09',
      'Gray/10': 'background-gray-10',
      'Gray/11': 'background-gray-11',
      'Blue/01': 'background-blue-01',
      'Blue/02': 'background-blue-02',
      'Blue/03': 'background-blue-03',
      'Blue/04 (basic)': 'background-blue-04',
      'Blue/05': 'background-blue-05',
      'Blue/06': 'background-blue-06',
      'Blue/07': 'background-blue-07',
      'Blue/08': 'background-blue-08',
      'Blue/09': 'background-blue-09',
      'Red/01': 'background-red-01',
      'Red/02': 'background-red-02',
      'Red/03': 'background-red-03',
      'Red/04': 'background-red-04',
      'Red/05': 'background-red-05',
      'Red/06': 'background-red-06',
      'Red/07': 'background-red-07',
      'Red/08': 'background-red-08',
      'Red/09': 'background-red-09',
      'Badge/P_bg': 'background-badge-p-bg',
      'Badge/P_txt': 'background-badge-p-txt'
    },
    COLOR: {
      'Common/White': 'color-white',
      'Gray/01': 'color-gray-01',
      'Gray/02': 'color-gray-02',
      'Gray/03': 'color-gray-03',
      'Gray/04': 'color-gray-04',
      'Gray/05': 'color-gray-05',
      'Gray/06': 'color-gray-06',
      'Gray/07': 'color-gray-07',
      'Gray/08': 'color-gray-08',
      'Gray/09': 'color-gray-09',
      'Gray/10': 'color-gray-10',
      'Gray/11': 'color-gray-11',
      'Blue/01': 'color-blue-01',
      'Blue/02': 'color-blue-02',
      'Blue/03': 'color-blue-03',
      'Blue/04 (basic)': 'color-blue-04',
      'Blue/05': 'color-blue-05',
      'Blue/06': 'color-blue-06',
      'Blue/07': 'color-blue-07',
      'Blue/08': 'color-blue-08',
      'Blue/09': 'color-blue-09',
      'Red/01': 'color-red-01',
      'Red/02': 'color-red-02',
      'Red/03': 'color-red-03',
      'Red/04': 'color-red-04',
      'Red/05': 'color-red-05',
      'Red/06': 'color-red-06',
      'Red/07': 'color-red-07',
      'Red/08': 'color-red-08',
      'Red/09': 'color-red-09',
      'Badge/P_bg': 'color-badge-p-bg',
      'Badge/P_txt': 'color-badge-p-txt'
    },
    BORDER_COLOR: {
      'Common/White': 'border-color-white',
      'Gray/01': 'border-color-gray-01',
      'Gray/02': 'border-color-gray-02',
      'Gray/03': 'border-color-gray-03',
      'Gray/04': 'border-color-gray-04',
      'Gray/05': 'border-color-gray-05',
      'Gray/06': 'border-color-gray-06',
      'Gray/07': 'border-color-gray-07',
      'Gray/08': 'border-color-gray-08',
      'Gray/09': 'border-color-gray-09',
      'Gray/10': 'border-color-gray-10',
      'Gray/11': 'border-color-gray-11',
      'Blue/01': 'border-color-blue-01',
      'Blue/02': 'border-color-blue-02',
      'Blue/03': 'border-color-blue-03',
      'Blue/04 (basic)': 'border-color-blue-04',
      'Blue/05': 'border-color-blue-05',
      'Blue/06': 'border-color-blue-06',
      'Blue/07': 'border-color-blue-07',
      'Blue/08': 'border-color-blue-08',
      'Blue/09': 'border-color-blue-09',
      'Red/01': 'border-color-red-01',
      'Red/02': 'border-color-red-02',
      'Red/03': 'border-color-red-03',
      'Red/04': 'border-color-red-04',
      'Red/05': 'border-color-red-05',
      'Red/06': 'border-color-red-06',
      'Red/07': 'border-color-red-07',
      'Red/08': 'border-color-red-08',
      'Red/09': 'border-color-red-09',
      'Badge/P_bg': 'border-color-badge-p-bg',
      'Badge/P_txt': 'border-color-badge-p-txt'
    }
  },
  BUTTON: {
    SIZE: {
      LARGE: 'large',
      MEDIUM: 'medium',
      SMALL: 'small'
    },
    TYPE: {
      DEFAULT: 'default',
      TEXT: 'text'
    }
  },
  CHECKBOX: {
    TYPE: {
      CHECKBOX: 'design-checkbox',
      ROUND: 'design-roundcheckbox',
      CHECK: 'design-check',
      LABEL: 'design-label',
      SWITCH: 'design-switch'
    }
  },
  DIALOG: {
    TYPE: {
      ALERT: 'is-alert',
      CONFIRM: 'is-confirm',
      CHECK: 'is-check',
      CONTENT: 'is-content',
      ONLY_IMAGE: 'is-onlyimage',
      ONLY_NOTIFICATION: 'is-only-notification'
    }
  }
}
